apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: kube-system
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
